### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by sr66139p** [babaissarkar/ssplot#1]
I found SSPlot on Flathub, and I see that the latest release mentions Flathub Support, but I don't see the Flatpak mentioned under Installation in the README.md file or a verification badge. Would you mind adding these so new users know it's official? Here's a link to the Flathub documentation for verification https://docs.flathub.org/docs/for-app-authors/verification

**Comment by babaissarkar** [comment]
Thanks for letting me know, I'll do it as soon as possible.

**Comment by babaissarkar** [comment]
Should be verified now. I've also added badges to the main README.
